version: '2.4'

services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://camunda-postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=camunda-postgres:5432
    links:
      - camunda-postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - camunda-postgres

  camunda-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda

  postgres:
      image: postgres:15
      ports:
        - "5432:5432"
      restart: always
      environment:
        POSTGRES_PASSWORD: core
        POSTGRES_USER: core

#  front-end:
#    build:
#      context: ./fake-frontend'
#      target: runner
#    volumes:
#      - ./fake-frontend:/app
#    command: npm run dev
#    ports:
#      - "3000:3000"
#    environment:
#      NODE_ENV: development