version: '2.4'

services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=postgres:5432
    links:
      - camunda-postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

  camunda-postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda

  postgres:
      image: postgres:15
      ports:
        - "5432:5432"
      restart: always
      environment:
        POSTGRES_PASSWORD: core
        POSTGRES_USER: core